import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import vm from 'node:vm';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const ja=JSON.parse(read('locales/ja.json')),en=JSON.parse(read('locales/en.json'));
function runtime(locale){const context=vm.createContext({TextEncoder,TextDecoder,console,Blob,Uint8Array,ArrayBuffer,DataView,Map,Set,Date});for(const file of [`locales/${locale}.js`,'i18n.js','file-codec.js','diff-engine.js'])vm.runInContext(read(file),context);return context;}
function book(name,rows){const data=new Map(rows.map((row,i)=>[i+1,new Map(row.map((v,c)=>[c,{v,t:'s',f:null,style:{},addr:String.fromCharCode(65+c)+(i+1)}]))]));return{name,kind:'csv',warnings:[],metadata:{},sheets:[{name:'Data',rows:data,maxRow:rows.length,maxCol:rows[0].length,metadata:{},warnings:[]}]};}
test('all Japanese and English keys and interpolation parameters match',()=>{assert.deepEqual(Object.keys(ja).sort(),Object.keys(en).sort());for(const k of Object.keys(ja)){const p=s=>[...new Set(s.match(/\{(?:p\d+|locale)\}/g)||[])].sort();assert.deepEqual(p(ja[k]),p(en[k]),k);assert.ok(en[k].trim(),k);}});
test('English messages contain no untranslated Japanese',()=>{for(const[k,s]of Object.entries(en))assert.ok(!/[\p{Script=Hiragana}\p{Script=Katakana}\p{Script=Han}]/u.test(s),k);});
test('each language has static searchable content, its own canonical and reciprocal links',()=>{for(const[l,p]of [['ja',''],['en','en/']]){const html=read(p+'index.html');assert.ok(html.includes(`lang="${l}"`));assert.ok(html.includes(`rel="canonical" href="https://makiabe.github.io/ExcelDiff/${p}"`));for(const code of ['ja','en','x-default'])assert.ok(html.includes(`hreflang="${code}"`));assert.ok(!html.includes('{{'));assert.ok(html.includes('<h1'));assert.ok(html.includes('id="faq"'));assert.ok(html.includes('application/ld+json'));assert.ok(html.includes(`locales/${l}.js`));}});
test('international pages use shared text-free mascot artwork and real HTML bubble text',()=>{const html=read('en/index.html');assert.ok(html.includes('assets/hero-cat-intl.avif'));assert.ok(html.includes('assets/bottom-cat-intl.avif'));assert.ok(html.includes('class="bubble"'));assert.ok(html.includes('the differences!'));assert.ok(!read('index.html').includes('class="bubble"'));});
test('international hero artwork has translatable CSS-positioned labels outside the speech bubble',()=>{const enHtml=read('en/index.html'),jaHtml=read('index.html');assert.ok(enHtml.includes('class="hero-labels"'));assert.ok(enHtml.includes('Cell changes'));assert.ok(enHtml.includes('Added &amp; deleted rows'));assert.ok(enHtml.includes('Formula &amp; format differences'));assert.ok(!jaHtml.includes('class="hero-labels"'));});
test('generated assets and visible version share the configured site version',()=>{const html=read('en/index.html'),version=JSON.parse(read('site.config.json')).version;assert.ok(html.includes(`id="appVersion">v${version}</span>`));assert.ok(html.includes(`app.js?v=${version}`));assert.ok(html.includes(`site.css?v=${version}`));});
test('sitemap lists both canonical URLs',()=>{const xml=read('sitemap.xml');assert.ok(xml.includes('<loc>https://makiabe.github.io/ExcelDiff/</loc>'));assert.ok(xml.includes('<loc>https://makiabe.github.io/ExcelDiff/en/</loc>'));});
test('runtime interpolation preserves data instead of interpreting it as a new placeholder',()=>{const c=runtime('en');assert.equal(c.ExcelDiffI18n.t('app.048',{p0:2}),'Sheets loaded: 2');assert.equal(c.ExcelDiffI18n.t('app.055',{p0:'{p1}'}),'Primary key: {p1}');assert.throws(()=>c.ExcelDiffI18n.t('missing'));assert.throws(()=>c.ExcelDiffI18n.t('app.048'));});
test('CSV primary keys find added, deleted and changed rows in both languages',()=>{for(const l of ['ja','en']){const c=runtime(l);const a=book('a.csv',[['ID','Name'],['1','Alpha'],['2','Beta']]),b=book('b.csv',[['ID','Name'],['1','ALPHA'],['3','Gamma']]);const r=c.ExcelDiffEngine.compareBooks(a,b,{primaryKey:'A'});assert.equal(r.stats.changedCells,1);assert.equal(r.stats.addedRows,1);assert.equal(r.stats.deletedRows,1);const ignored=c.ExcelDiffEngine.compareBooks(a,b,{primaryKey:'A',ignoreCase:true});assert.equal(ignored.stats.changedCells,0);assert.equal(ignored.stats.ignoredCells,1);}});
test('first row changes are compared rather than discarded',()=>{const c=runtime('en'),a=book('a.csv',[['ID','Name'],['1','Alpha']]),b=book('b.csv',[['ID','Display name'],['1','Alpha']]);assert.equal(c.ExcelDiffEngine.compareBooks(a,b).stats.changedCells,1);});
test('duplicate keys fail visibly, with localized messages',()=>{const c=runtime('en'),a=book('a.csv',[['ID','Name'],['1','Alpha'],['1','Beta']]);assert.throws(()=>c.ExcelDiffEngine.compareBooks(a,a,{primaryKey:'A'}),/Duplicate primary keys/);});
test('a third language only needs a dictionary and a registry entry',()=>{const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'excel-diff-i18n-'));try{for(const f of ['src/index.template.html','scripts/build.mjs','locales/ja.json','locales/en.json','site.config.json']){fs.mkdirSync(path.dirname(path.join(tmp,f)),{recursive:true});fs.copyFileSync(path.join(root,f),path.join(tmp,f));}fs.copyFileSync(path.join(tmp,'locales/en.json'),path.join(tmp,'locales/es.json'));const config=JSON.parse(read('site.config.json'));config.locales.push({code:'es',label:'Español',path:'es/',dir:'ltr',artwork:'international'});fs.writeFileSync(path.join(tmp,'site.config.json'),JSON.stringify(config));execFileSync(process.execPath,[path.join(tmp,'scripts/build.mjs')]);const html=fs.readFileSync(path.join(tmp,'es/index.html'),'utf8');assert.ok(html.includes('lang="es"'));assert.ok(html.includes('assets/hero-cat-intl.avif'));assert.ok(html.includes('locales/es.js'));assert.ok(fs.readFileSync(path.join(tmp,'sitemap.xml'),'utf8').includes('/es/</loc>'));}finally{fs.rmSync(tmp,{recursive:true,force:true});}});
