import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const config=JSON.parse(read('site.config.json'));
const template=read('src/index.template.html');
const reference=JSON.parse(read('locales/ja.json'));
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json=s=>JSON.stringify(s).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');
const write=(p,data)=>{fs.mkdirSync(path.dirname(path.join(root,p)),{recursive:true});fs.writeFileSync(path.join(root,p),data);};
const placeholders=s=>[...new Set([...s.matchAll(/\{(p\d+|locale)\}/g)].map(m=>m[1]))].sort().join(',');
const codes=new Set(),paths=new Set();
if(!config.siteUrl.endsWith('/')||new URL(config.siteUrl).protocol!=='https:')throw Error('siteUrl must be an HTTPS URL ending in /.');
for(const locale of config.locales){
 if(!/^[a-z]{2,3}(?:-[A-Za-z0-9]{2,8})*$/.test(locale.code)||!['ltr','rtl'].includes(locale.dir))throw Error('Invalid locale configuration.');
 if(locale.path!==''&&!/^[a-z0-9-]+\/$/.test(locale.path))throw Error('Locale path must be empty or a directory such as en/.');
 if(codes.has(locale.code)||paths.has(locale.path))throw Error('Duplicate locale code or path.');
 codes.add(locale.code);paths.add(locale.path);
}
if(!codes.has(config.fallbackLocale))throw Error('Fallback locale is not published.');
for(const locale of config.locales){
 const messages=JSON.parse(read(`locales/${locale.code}.json`));
 const keys=Object.keys(reference);
 if(Object.keys(messages).length!==keys.length)throw Error(`Translation key count differs: ${locale.code}`);
 for(const key of keys){
  if(typeof messages[key]!=='string'||!messages[key].trim())throw Error(`Missing translation: ${locale.code} ${key}`);
  if(placeholders(messages[key])!==placeholders(reference[key]))throw Error(`Placeholder mismatch: ${locale.code} ${key}`);
 }
 const base=locale.path?'../':'',url=new URL(locale.path,config.siteUrl).href;
 const intl=locale.artwork!=='ja';
 const vars={...messages,lang:locale.code,dir:locale.dir,base,
  'asset.hero':base+'assets/'+(intl?'hero-cat-intl.avif':'hero-cat.webp'),
  'asset.bottom':base+'assets/'+(intl?'bottom-cat-intl.avif':'bottom-cat.webp'),
  'asset.heroWidth':'640','asset.heroHeight':'320',
  'asset.bottomWidth':intl?'560':'480','asset.bottomHeight':intl?'191':'160',
  'raw.canonical':`<link rel="canonical" href="${escape(url)}">`,
  'raw.alternates':config.locales.map(l=>`<link rel="alternate" hreflang="${l.code}" href="${escape(new URL(l.path,config.siteUrl).href)}">`).join('\n')+`\n<link rel="alternate" hreflang="x-default" href="${escape(new URL(config.locales.find(l=>l.code===config.fallbackLocale).path,config.siteUrl).href)}">`,
  'raw.social':`<meta property="og:type" content="website"><meta property="og:site_name" content="Excel Diff"><meta property="og:title" content="${escape(messages['seo.title'])}"><meta property="og:description" content="${escape(messages['seo.description'])}"><meta property="og:url" content="${escape(url)}"><meta property="og:locale" content="${locale.code==='ja'?'ja_JP':locale.code==='en'?'en_US':locale.code.replace('-','_')}"><meta name="twitter:card" content="summary">`,
  'raw.structured':`<script type="application/ld+json">${json({'@context':'https://schema.org','@type':'WebApplication',name:'Excel Diff',url,description:messages['seo.applicationDescription'],applicationCategory:'UtilitiesApplication',operatingSystem:'Any',inLanguage:locale.code,browserRequirements:'Requires JavaScript and a modern web browser',offers:{'@type':'Offer',price:'0',priceCurrency:'USD'}})}</script>`,
  'raw.stylesheet':`<link rel="stylesheet" href="${base}site.css?v=${config.version}">`,
  'raw.languageSwitcher':`<div class="locale-switcher" role="group" aria-label="${escape(messages['nav.language'])}">${config.locales.map(l=>`<a href="${base}${l.path||'./'}" lang="${l.code}" hreflang="${l.code}"${l.code===locale.code?' aria-current="page"':''}>${escape(l.label)}</a>`).join('')}</div>`,
  'raw.heroBubble':intl?`<p class="bubble">${escape(messages['mascot.heroBubble'])}</p>`:'',
  'raw.bottomBubble':intl?`<p class="bubble">${escape(messages['mascot.bottomBubble'])}</p>`:''
 };
 const html=template.replace(/\{\{([A-Za-z0-9_.-]+)\}\}/g,(_,key)=>{
  if(!Object.hasOwn(vars,key))throw Error(`Unknown template key ${key}`);
  return key.startsWith('raw.')?vars[key]:escape(vars[key]);
 });
 if(/\{\{[A-Za-z0-9_.-]+\}\}/.test(html))throw Error('Unresolved template placeholder.');
 write(locale.path+'index.html',html);
 write(`locales/${locale.code}.js`,`/* Generated by npm run build; edit ${locale.code}.json instead. */\nglobalThis.ExcelDiffLocale=${json({locale:locale.code,messages})};\n`);
 console.log(`Built ${locale.code}: ${locale.path}index.html (${keys.length} translation keys)`);
}
const alternates=config.locales.map(l=>`    <xhtml:link rel="alternate" hreflang="${l.code}" href="${escape(new URL(l.path,config.siteUrl).href)}"/>`).join('\n');
write('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n${config.locales.map(l=>`  <url>\n    <loc>${escape(new URL(l.path,config.siteUrl).href)}</loc>\n${alternates}\n  </url>`).join('\n')}\n</urlset>\n`);
write('.nojekyll','');
